In [1]:
import pandas as pd

weather_data = {
    "Outlook": ["Sunny", "Sunny", "Overcast", "Rain", "Rain", "Rain", "Overcast",
                "Sunny", "Sunny", "Rain", "Sunny", "Overcast", "Overcast", "Rain"],
    "Temperature": ["Hot", "Hot", "Hot", "Mild", "Cool", "Cool", "Cool", "Mild",
                    "Cool", "Mild", "Mild", "Mild", "Hot", "Mild"],
    "Humidity": ["High", "High", "High", "High", "Normal", "Normal",
                 "Normal", "High", "Normal", "Normal", "Normal",
                 "High", "Normal", "High"],
    "Wind": ["Weak", "Strong", "Weak", "Weak", "Weak", "Strong",
             "Strong", "Weak", "Weak", "Weak", "Strong", "Strong", "Weak", "Strong"],
    "Play Tennis": ["No", "No", "Yes", "Yes", "Yes", "No", "Yes",
                    "No", "Yes", "Yes", "Yes", "Yes", "Yes", "No"]
}

df = pd.DataFrame(weather_data)
print(df)

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [2]:
df['Temperature'].value_counts()

Mild    6
Hot     4
Cool    4
Name: Temperature, dtype: int64

In [3]:
df.head(5)

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [4]:
df.tail(3)

     Outlook Temperature Humidity    Wind Play Tennis
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [5]:
import numpy as np
a = [1, 2, 3, 4, 5]
my_array = np.array(a)
print(my_array)

[1 2 3 4 5]

In [6]:
import numpy as np
lst = ([[1, 2], [3, 4], [5, 6]])
a = np.array(lst)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

In [7]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1 = a+10
print(a+10)

[[11 12]
 [13 14]
 [15 16]]

In [9]:
sum1 = np.sum(a)
print(sum1)

21

In [10]:
mean1 = np.mean(a)
print(mean1)

3.5